#% RAML 1.0 AccountPaymentInfoDto
{
    "type": "object",
    "properties": {
        "structuredReference": {
            "type": "string"
        },
        "bicCode": {
            "type": "string"
        },
        "accountNumber": {
            "type": "string"
        }
    }
}