#% RAML 1.0 AccommodationDto
{
    "type": "object",    
    "properties": {
        "mealPlan": {
            "type": "string"
        },
        "roomProfiles": {
            "type": "RoomProfileDto[]",
            "minItems": 1
        }
    }
}
