#% RAML 1.0 AlternativeFlightsDto
{
    "type": "object",
    "properties": {
        "alternativeFlights": {
            "type": "AlternativeFlightPackage[]"
        },
        "searchResultid": {
            "type": "string"
        }
    }
}