#% RAML 1.0 CalculatedExtraSegmentDto
{
    "type": "object",
    "properties": {
        "type":{
            "type": "SegmentType"
        },
        "calculatedOption": {
            "type": "string"
        },
        "price": {
            "type": "number",
            "format": "double"
        }
    }
}