#% RAML 1.0 CalculatedExtraDto
{
    "type": "object",
    "properties": {
        "id": {
            "type": "SelectedExtraId"
        },
        "recipients": {
              "type": "CalculatedExtraRecipientDto[]"
        }
    }
}