#% RAML 1.0 ContactDetailsDto
{
    "type": "object",
    "properties": {
        "leadPassengerId": {
            "type": "string"
        },
        "streetName": {
            "type": "string"
        },
        "houseNumber": {
            "type": "string"
        },
        "postalCode": {
            "type": "string"
        },
        "city": {
            "type": "string"
        },
        "country": {
            "type": "string"
        },
        "countryCode": {
            "type": "string"
        },
        "phoneNumber": {
            "type": "string"
        },
       "email": {
            "type": "string"
        }
    }
}