#% RAML 1.0 DateRangeDto
{
    "type": "object",
    "properties": {
        "days": {
            "type": "number",
            "format" : "int"
        },
        "nights": {
            "type": "number",
            "format" : "int"
        },
        "startDate": {
            "type": "string",
            "example":"2017-05-16T00:45:00Z"
        },
        "endDate": {
            "type": "string",
            "example":"2017-05-24T00:45:00Z"
        }
    }
}
