#% RAML 1.0 ExtraOptionDto
{
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "displayOrder?": {
            "type": "number",
            "format": "int"
        },
        "price?":{
            "type": "number",
            "format": "double"
        }

    }
}
