#% RAML 1.0 ExtraRecipientDto
{
    "type": "object",
    "properties": {
        "type":{
            "type": "ExtraRecipientType"
        },
        "id?": {
            "type": "string"
        },
        "segments": {
            "type": "ExtraSegmentDto[]"
        }
    }
}
