#% RAML 1.0 ExtraDetailsDto
{
    "type": "object",
    "properties": {
        "passengerId?": {
           "type": "string"
        },
        "optionCode": {
           "type": "string"
        },
        "optionValue?": {
           "type": "string"
        }
    }
}