#% RAML 1.0 FilterType

{
   "type": "string",
   "enum": ["EQUALS", "NOT_EQUAL", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "LESS_THAN", "LESS_THAN_OR_EQUALS", "GREATER_THAN", "GREATER_THAN_OR_EQUALS", "IN_RANGE"]
}