#% RAML 1.0 FlightPassengerDto
{
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "seat?": {
            "type": "array",
            "items":{
                "type": "string"
            }
        },
        "withInfant?":{
            "type": "string"
        }
    }
}
