#% RAML 1.0 FlightExtraDto
{
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "inbound": {
            "type": "ExtraDetailsDto[]"
        },
        "outbound": {
            "type": "ExtraDetailsDto[]"
        }
    }
}