#%RAML 1.0 ModificationHistoryDto

{
    type: object,
    properties: {
        author: {
            type: string
        },
        date: {
            type: number,
            format: long
        },
        action: {
            type: ModificationHistoryAction
        },
        table: {
            type: ModificationHistoryTable
        }
    }
}