#% RAML 1.0 ModificationHistoryTable

{
   type: string,
   enum: ['INCLUDED_TRANSFER', 'PAID_TRANSFER', 'INCLUDED_LUGGAGE', 'PAID_LUGGAGE', 'CARRIER', 'AIRPORT', 'SEASON', 'CATALOGUE', 'BOOKING_CATEGORY', 'BRAND']
}
