#% RAML 1.0 PageDto
{
    "type": "object",
    "properties": {
        "total": {
            "type": "number",
            "format": "int"
        },
        "pageSize": {
            "type": "number",
            "format": "int"
        },
        "pageNumber": {
            "type": "number",
            "format": "int"
        }
    }
}
