#% RAML 1.0 PassengerPriceLineItemDto
{
    "type": "object",
    "properties": {
        "paxId": {
            "type": "string"
        },
        "selection?": {
             "type": "string"
        },
        "price?": {
             "type": "number",
             "format": "double"
        }
    }
}
