#% RAML 1.0 PassengerDto
{
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "firstName": {
            "type": "string"
        },
        "lastName?": {
            "type": "string"
        },
        "gender": {
            "type": "string"
        },
         "ageCode?": {
            "type": "AgeCode"
        }
    }
}
