#% RAML 1.0 PriceCalculationRequestDto
 {
     "type": "object",
     "properties": {
      "id": {
           "type": "SelectedExtraId"
      },
      "recipients": {
           "type": "PriceExtraRecipientDto[]"
         }
     }
 }