#% RAML 1.0 SegmentOptionDto
{
    "type": "object",
    "properties": {
        "type":{
            "type": "SegmentType"
        },
        "selectedOption": {
            "type": "string"
        }
    }
}