#% RAML 1.0 TripExtraDto
{
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name?": {
            "type": "string"
        },
       "wholeTrip": {
            "type": "ExtraDetailsDto[]"
       }
    }
}