#%RAML 1.0 DictionaryDto

{
    type: object,
    properties: {
        id: {
             type: number,
             format: int,
             required: false
        },
        value: {
             type: string
        }
    }
}