#%RAML 1.0 IncludedTransferPageDto

{
    type: PageDto,
    properties: {
        items: {
             type: array,
             items:{
                 type: IncludedTransferDto
             }
        }
    }
}