#%RAML 1.0 BaseConfigurationDto

{
    "type": "object",
    "properties": {
        "id?": {
             "type": "number",
             "format": "int"
        },
        "season": {
             "type": DictionaryDto
        }
    }
}