#%RAML 1.0 BaseIncludedConfigurationDto

{
    "type": BaseConfigurationDto,
    "properties": {
        "brand": {
             "type": BrandDto
        },
        "catalogue": {
             "type": DictionaryDto
        },
        "arrivalAirport": {
             "type": DictionaryDto
        }
    }
}